name: Build and Test
on: [push, pull_request]
permissions:
  contents: read

jobs:
  build:
    name: Go CI
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ["1.21", "1.22"]
    steps:
      - name: Check out source
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b #v4.1.4
      - name: Set up Go
        uses: actions/setup-go@cdcb36043654635271a94b9a6d1392de5bb323a7 #v5.0.1
        with:
          go-version: ${{ matrix.go }}
      - name: Use lint cache
        uses: actions/cache@704facf57e6136b1bc63b828d79edcd491f0ee84 # v3.3.2
        with:
          path: |
            ~/.cache/golangci-lint
          key: go-lint-${{ matrix.go }}-${{ hashFiles('./go.sum') }}
          restore-keys: go-lint-${{ matrix.go }}
      - name: Stablilize testdata timestamps
        run: |
          bash ./.github/stablilize_testdata_timestamps.sh "${{ github.workspace }}"
      - name: Install Linters
        run: "go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.58.1"
      - name: Build
        run: go build ./...
      - name: Test
        run: |
          sh ./run_tests.sh
